// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL4HBPfoohiK69l4dG-Lmeo7tsh-Wuc0A',
    appId: '1:724084477848:web:acabf7b6d2d4e7703be5ed',
    messagingSenderId: '724084477848',
    projectId: 'sign-in-8cfcf',
    authDomain: 'sign-in-8cfcf.firebaseapp.com',
    storageBucket: 'sign-in-8cfcf.firebasestorage.app',
    measurementId: 'G-YV1JN8TKT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLe2Wj35BNj3ZT-T_nqOEMuBdiJn3FGqE',
    appId: '1:724084477848:android:a4db52e16e4b8da83be5ed',
    messagingSenderId: '724084477848',
    projectId: 'sign-in-8cfcf',
    storageBucket: 'sign-in-8cfcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARUF778d1KsnnpIn8Eqmhit2xnhz88k5Q',
    appId: '1:724084477848:ios:a9251c48bed6d28d3be5ed',
    messagingSenderId: '724084477848',
    projectId: 'sign-in-8cfcf',
    storageBucket: 'sign-in-8cfcf.firebasestorage.app',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARUF778d1KsnnpIn8Eqmhit2xnhz88k5Q',
    appId: '1:724084477848:ios:a9251c48bed6d28d3be5ed',
    messagingSenderId: '724084477848',
    projectId: 'sign-in-8cfcf',
    storageBucket: 'sign-in-8cfcf.firebasestorage.app',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL4HBPfoohiK69l4dG-Lmeo7tsh-Wuc0A',
    appId: '1:724084477848:web:e48f52fabe34651e3be5ed',
    messagingSenderId: '724084477848',
    projectId: 'sign-in-8cfcf',
    authDomain: 'sign-in-8cfcf.firebaseapp.com',
    storageBucket: 'sign-in-8cfcf.firebasestorage.app',
    measurementId: 'G-3TGZG91S33',
  );

}